server:
  port: 9084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb
    username: root
    password: 123456 # MySQL kullanıcı şifrenizi buraya girin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
