server:
  port: 9083

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:mysql://localhost:3306/transferdb
    username: root
    password: 123456 # MySQL kullanıcı şifrenizi buraya girin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/